### ISSUE TITLE
Parsing Error generated if no reviews and PLUGIN_SDATA_REVIEW_USE_DEFAULT === 'false'

### ISSUE THREAD

**Issue by mc12345678** [torvista/Zen_Cart-Structured_Data#32]
When https://github.com/torvista/Zen_Cart-Structured_Data/blob/5d93f1c454019005da3f815d23a7010fa63b63da/files/includes/templates/YOUR_TEMPLATE/jscript/jscript_plugin_structured_data.php#L20 is modified to prevent display of review information on product that do not have reviews, a parsing error occurs.  The error can be identified as: Missing '}' or object member name.

This appears to be a result of a comma often being applied to the end of a grouping instead of prefixing data that follows when it is known that something came before.

Again, this specifically occurs when:
````diff
- define('PLUGIN_SDATA_REVIEW_USE_DEFAULT', 'true'); // if no product review, use a default value to stop Google warnings
+ define('PLUGIN_SDATA_REVIEW_USE_DEFAULT', 'false'); // if no product review, use a default value to stop Google warnings
````
and
the product does not have any reviews. Yes, a warning is still identified because there is no review information; however, it is still valid.

**Comment by torvista** [comment]
fixed in https://github.com/torvista/Zen_Cart-Structured_Data/commit/439d97c5c5030fcb8242568141d1bc5be9640734
