### ISSUE TITLE
PHP Notice generated when $_SERVER['HTTP_HOST'] isn't set

### ISSUE THREAD

**Issue by lat9** [torvista/Zen_Cart-Structured_Data#43]
https://github.com/torvista/Zen_Cart-Structured_Data/blob/6b312c24b8b27b28a05bcdb954a7dd262311fd4d/files/includes/templates/YOUR_TEMPLATE/jscript/jscript_plugin_structured_data.php#L214

**Comment by torvista** [comment]
This should fix it
https://github.com/torvista/Zen_Cart-Structured_Data/commit/adea3ebec92a263936343b4132eb3b13d54d5fa7
